# Generated by Django 2.2.1 on 2019-09-12 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image_url', models.URLField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('likes_count', models.IntegerField(blank=True, null=True)),
                ('publish_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'url')},
            },
        ),
    ]
