# Generated by Django 2.2.1 on 2019-09-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
